version: '2.4'

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local
